// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpOZ71hyr29bRXqKu4zNtfC4X6DHuYgg',
    appId: '1:149563575591:web:7050a22abbf53f67322d02',
    messagingSenderId: '149563575591',
    projectId: 'whispr-e0a09',
    authDomain: 'whispr-e0a09.firebaseapp.com',
    storageBucket: 'whispr-e0a09.firebasestorage.app',
    measurementId: 'G-S77LDDTQFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDazn9as0rK7zn6Obz8JP1MUHGwIIJO_3E',
    appId: '1:149563575591:android:6e66092605040c2f322d02',
    messagingSenderId: '149563575591',
    projectId: 'whispr-e0a09',
    storageBucket: 'whispr-e0a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbTiGfF_Evd6_iipmmpPtvdFdx3k1qhMQ',
    appId: '1:149563575591:ios:bc0da4638b02e283322d02',
    messagingSenderId: '149563575591',
    projectId: 'whispr-e0a09',
    storageBucket: 'whispr-e0a09.firebasestorage.app',
    iosBundleId: 'com.example.whispr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbTiGfF_Evd6_iipmmpPtvdFdx3k1qhMQ',
    appId: '1:149563575591:ios:bc0da4638b02e283322d02',
    messagingSenderId: '149563575591',
    projectId: 'whispr-e0a09',
    storageBucket: 'whispr-e0a09.firebasestorage.app',
    iosBundleId: 'com.example.whispr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVpOZ71hyr29bRXqKu4zNtfC4X6DHuYgg',
    appId: '1:149563575591:web:c2c986ea891417c0322d02',
    messagingSenderId: '149563575591',
    projectId: 'whispr-e0a09',
    authDomain: 'whispr-e0a09.firebaseapp.com',
    storageBucket: 'whispr-e0a09.firebasestorage.app',
    measurementId: 'G-B4JDNHR7QW',
  );

}